### PR TITLE
Add Nigel as Community Manager and Kay as Tech Docs lead

### PR DESCRIPTION
**Pull request by OrlinVasilev**
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>

### CODE REVIEW

**Review by sunjayBhatia — APPROVED** [review]

**Review by sunjayBhatia — COMMENTED** [review]
LGTM, assuming per the governance documentation this stuff doesn't need a vote?

**Review by sunjayBhatia — APPROVED** [review]

**Comment by skriss** [comment]
> LGTM, assuming per the governance documentation this stuff doesn't need a vote?

From my read it does not for these roles.

**Comment by youngnick** [comment]
Yes, we haven't yet got enough participation in the SIGs to need a vote there, although I'd hope we'll need that eventually.

**Comment by youngnick** [comment]
@tsaarni, @stevesloka, any thoughts before we merge?

**Comment by stevesloka** [comment]
@youngnick I'm not sure who Nigel or Kay is, but have been absent recently from meetings, so no vote from me to be completely honest. 😀

**Comment by tsaarni** [comment]
👍

**Pull request merged**
